##
## Makefile for Makefile in /home/gogo/rendu/dante
## 
## Made by Gauthier Cler
## Login   <cler_g@epitech.net>
## 
## Started on  Sat May 21 14:37:04 2016 Gauthier Cler
## Last update Sat May 21 14:43:06 2016 Gauthier Cler
##

all:
		(cd generateur; make all)
		(cd profondeur; make all)
		(cd largeur; make all)
		(cd astar; make all)
		(cd tournoi; make all)

clean:
		(cd generateur; make clean)
		(cd profondeur; make clean)
		(cd largeur; make clean)
		(cd astar; make clean)
		(cd tournoi; make clean)	

fclean:
		(cd generateur; make fclean)
		(cd profondeur; make fclean)
		(cd largeur; make fclean)
		(cd astar; make fclean)
		(cd tournoi; make fclean)

re:
		(cd generateur; make re)
		(cd profondeur; make re)
		(cd largeur; make re)
		(cd astar; make re)
		(cd tournoi; make re)
